// Compile as: gcc -g -Wall -pthread filename.c -o filename

#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <semaphore.h>
#include <unistd.h>
#include <time.h>

#define N_TICKETS 100		//total tickets available for sale
#define N_CLIENTS 10		//total client (threads)
#define MAX_RUN_THREADS 4	//max clients threads running at the same time


int sold=0; // sold tickets
pthread_t my_thread[N_CLIENTS]; // threads id
int ids[N_CLIENTS]; // saves id from client threads

//sync resources
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER; //equivalent to pthread_mutex_init() with attr specified as NULL
sem_t sem_threads_limit;


void *generate_requests(void* id_ptr) {
	int id = *((int *)id_ptr);
	int new_request = 0;
	
	while(1){	

		// control the maximum threads working at the same time (MAX_RUN_THREADS)
		???
		
		// control the access to the 'sold' shared variable
		???
		
		//if tickets are sold out then release sync resources and exit
		if(sold==N_TICKETS){
			//1st release resources that were allocated then exit thread
			???
			???
			???
		}
		else{
			
			new_request=rand()% ??? ; //random number from 1 to 10
			
			if( (sold+new_request) > N_TICKETS ){ //if new request exceeds remaining tickets
				
				//update new request to buy all the remaining tickets
				new_request = N_TICKETS-sold;
			}
			
			sold += new_request;
		}
		
		printf("New request of %d tickets was generated by thread %d\n",new_request,id);
		
		??? // control the access to the 'sold' shared variable
		sleep(2); //for debug purposes to visualize how many threads are executing
		??? // control the maximum threads working at the same time (MAX_RUN_THREADS)
	}
}

int main(void) {
	
	srand(time(NULL));
	
	int i;
	sem_init(&sem_threads_limit,0, ??? ); //set semaphore initial counter value

	// create threads (clients)
	for (i = 0; i < N_CLIENTS; i++){
		ids[i] = i;
		if(pthread_create(&my_thread[i], NULL, generate_requests, &ids[i]) != 0){
			perror("Error creating Thread!");
			exit(0);
		}
		printf("Thread %d created\n", ids[i]);
	}

	// wait until all threads client finish
	for (i = 0; i < N_CLIENTS; i++){
		pthread_join(my_thread[i], NULL);
		printf("Thread %d joined\n", i);
	}
	
	printf("Total tickets sold = %d\n",sold);

	// destroy mutex
	???
	
	//destroy semaphore
	???

	exit(0);
}
